### ISSUE TITLE
Chapter 2 - The Whole Game

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/py-pkgs#6]
The System setup chapter is currently being drafted by @ttimbers.

**Comment by TomasBeuzen** [comment]
@ttimbers what version of Python are you using? In this chapter you use the following code: 

'a.astype("string")`

This code fails for me. I thought that this syntax was deprecated in Python 3 in favour of the following:

`a.astype("str")`

I've changed this in the chapter for now so I could knit it. Hopefully you're still able to knit too.

**Comment by ttimbers** [comment]
Yes, that latter syntax works, and I have updated it to that now. It turns out that I had both syntaxes in the book. 

I am running modern Python (version 3.7.6!) however I think I was experimenting between different things due to [this stack overflow post](https://stackoverflow.com/questions/39092067/pandas-dataframe-convert-column-type-to-string-or-categorical)

And there, they don't suggest `"str"`, the suggest `str` - which also works!!! So, of `"str"` and `str`, which do you prefer @TomasBeuzen ?

**Comment by TomasBeuzen** [comment]
I prefer "str". To keep it consistent with "category" (because `.astype(category)` doesn't work, but `.astype("category")` does...).

It's all the syntax used in the [Pandas `.astype` documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.astype.html).

**Comment by ttimbers** [comment]
@TomasBeuzen @kvarada - can either of you please proof read this document? Ideally before beginning to end of next week?

**Comment by TomasBeuzen** [comment]
@ttimbers I went through the chapter in detail and it's really great. Have pushed all my changes which were mostly typos and word clarifications. My two big comments:

1. Every time I `git push`ed during the tutorial I got a build and release error email from GitHub. I was thinking it might just go away after I got further along but it didn't so I finally went and looked at the error. Screenshot below - I'm not familiar with GH actions yet so before I try debug it I thought I'd see if you knew the solution;

<img width="1103" alt="Screen Shot 2020-02-23 at 5 12 32 PM" src="https://user-images.githubusercontent.com/40379073/75123835-e0b40f00-565f-11ea-90d4-5dec20ee4cb1.png">

2. You've already taken the name `foocat` on Read the Doc and testPyPI (in fact I see foocat1, foocat2, foocat3, foocat4 on testPyPI!) so nobody else can use those. I've added words to that effect so that readers know to start with a unique package name.

**Comment by ttimbers** [comment]
That error is due to your not so stylish Python code 😜. The CI runs flake8 and it's pretty particular... I will add a note about this to the chapter (deferring to later chapters on how flake8 works) but I should have a not on how to deal with email notifications, as they likely want to turn them off...

**Comment by ttimbers** [comment]
And thanks for the note on the name `foocat` - that was an oversight. In R it's not an issue because I would never have the students submit the package to CRAN (and I don't think there's a test CRAN). It would only ever live on GitHub, and so it wouldn't be an issue. I appreciate your added words to make this work for this chapter.

**Comment by ttimbers** [comment]
More fixes to address:

### section 2.1
Later chapters will focus on the oter components of the boilerplate, which can be used to refine your package and packaging process with, for example, quality documentation, continuous integration testing, version bumping, etc.

The word ‘other’ was misspell.

### 2.7 Testing
```
{pyt{python foocat-test, eval = FALSE}m foocat import foocat import pandas as pd
> 
> def test_catbind(): a = pd.Categorical(["character", "hits", "your", "eyeballs"]) b = pd.Categorical(["but", "integer", "where it", "counts"]) assert ((foocat.catbind(a, b)).codes == [1, 4, 7, 3, 0, 5, 6, 2]).all() assert ((foocat.catbind(a, b)).categories == ["but", "character", "counts", "eyeballs", "hits", "integer", "where it", "your"]).all()
> Error in the code for the code chunk
> > here the "{phy" is repeated
> > the code chunk is not closed with 
```
This affect the whole document from that point downwards, so all next code chunks are texts, and all the explanations are inside code-chunks
